site_name: 'Read The Docs Jekyll Theme'
site_description: 'Port of the Read the Docs theme to Jekyll to use with GitHub Pages.'
repo_url: 'https://github.com/bridgecrewio/checkov-theme/'
repo_name: 'GitHub'
docs_dir: 'docs/'
site_dir: '_site_mkdocs/'
theme: 'checkov-theme'
prev_next_buttons_location: 'both'
copyright: 'palo_alto_networks'
