title: Read The Docs Jekyll Theme
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.
remote_theme: bridgecrewio/checkov-theme

# Theme settings:
site_author: Carlos Pereira Atencio
repo_url: "https://github.com/bridgecrewio/checkov-theme/"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
